/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sem6.aula2;

import java.awt.Font;

/**
 *
 * @author IFTM
 */
public class Exemplo02 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo2
     */
    public Exemplo02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtNormal = new javax.swing.JRadioButton();
        rbtNegrito = new javax.swing.JRadioButton();
        rbtItalico = new javax.swing.JRadioButton();
        rbtNegritoItalico = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfTexto = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbtNormal);
        rbtNormal.setText("Normal");
        rbtNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNormalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtNegrito);
        rbtNegrito.setText("Negrito");
        rbtNegrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNegritoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtItalico);
        rbtItalico.setText("Itálico");
        rbtItalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtItalicoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtNegritoItalico);
        rbtNegritoItalico.setText("Negrito/Itálico");
        rbtNegritoItalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNegritoItalicoActionPerformed(evt);
            }
        });

        tfTexto.setText("Mostra a mudança no estilo da fonte");
        jScrollPane2.setViewportView(tfTexto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtNormal)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtNegritoItalico)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtNegrito)
                                .addGap(18, 18, 18)
                                .addComponent(rbtItalico)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtNormal)
                    .addComponent(rbtNegrito)
                    .addComponent(rbtItalico))
                .addGap(34, 34, 34)
                .addComponent(rbtNegritoItalico)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtNegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNegritoActionPerformed
        // TODO add your handling code here:
        tfTexto.setFont(new Font("Serif", Font.PLAIN, 14));
        if(rbtNegrito.isSelected())
            tfTexto.setFont(new Font("Serif", Font.BOLD, 14));
    }//GEN-LAST:event_rbtNegritoActionPerformed

    private void rbtNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNormalActionPerformed
        // TODO add your handling code here:
        if(rbtNormal.isSelected())
            tfTexto.setFont(new Font("Serif", Font.PLAIN, 14));
    }//GEN-LAST:event_rbtNormalActionPerformed

    private void rbtItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtItalicoActionPerformed
        // TODO add your handling code here:
        tfTexto.setFont(new Font("Serif", Font.PLAIN, 14));
        if(rbtItalico.isSelected())
            tfTexto.setFont(new Font("Serif", Font.ITALIC, 14));
    }//GEN-LAST:event_rbtItalicoActionPerformed

    private void rbtNegritoItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNegritoItalicoActionPerformed
        // TODO add your handling code here:
        tfTexto.setFont(new Font("Serif", Font.PLAIN, 14));
        if(rbtNegritoItalico.isSelected())
            tfTexto.setFont(new Font("Serif", Font.BOLD + Font.ITALIC, 14));
    }//GEN-LAST:event_rbtNegritoItalicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtItalico;
    private javax.swing.JRadioButton rbtNegrito;
    private javax.swing.JRadioButton rbtNegritoItalico;
    private javax.swing.JRadioButton rbtNormal;
    private javax.swing.JTextPane tfTexto;
    // End of variables declaration//GEN-END:variables
}
