/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.iftm.view;

import br.edu.iftm.logic.Conversor;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabricio
 */
public class ConversorTemperaturaView extends javax.swing.JFrame {

    /**
     * Creates new form ConversorTemperaturaView
     */
    public ConversorTemperaturaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDe = new javax.swing.ButtonGroup();
        btgPara = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tfdTemperaturaDe = new javax.swing.JTextField();
        tfdTemperaturaPara = new javax.swing.JTextField();
        lblTemperaturaDe = new javax.swing.JLabel();
        lblTemperaturaPara = new javax.swing.JLabel();
        rbtCelsiusDe = new javax.swing.JRadioButton();
        rbtFahrenheitDe = new javax.swing.JRadioButton();
        rbtKelvinDe = new javax.swing.JRadioButton();
        rbtKelvinPara = new javax.swing.JRadioButton();
        rbtFahrenheitPara = new javax.swing.JRadioButton();
        rbtCelsiusPara = new javax.swing.JRadioButton();
        btnConverter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Temperatura");

        lblTemperaturaDe.setText("Converter de:");
        lblTemperaturaDe.setToolTipText("");

        lblTemperaturaPara.setText("Para:");

        btgDe.add(rbtCelsiusDe);
        rbtCelsiusDe.setText("Celsius");

        btgDe.add(rbtFahrenheitDe);
        rbtFahrenheitDe.setText("Fahrenheit");

        btgDe.add(rbtKelvinDe);
        rbtKelvinDe.setText("Kelvin");

        btgPara.add(rbtKelvinPara);
        rbtKelvinPara.setText("Kelvin");

        btgPara.add(rbtFahrenheitPara);
        rbtFahrenheitPara.setText("Fahrenheit");

        btgPara.add(rbtCelsiusPara);
        rbtCelsiusPara.setText("Celsius");

        btnConverter.setText("Converter");
        btnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdTemperaturaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemperaturaDe)
                    .addComponent(rbtKelvinDe)
                    .addComponent(rbtFahrenheitDe)
                    .addComponent(rbtCelsiusDe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConverter)
                    .addComponent(tfdTemperaturaPara, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemperaturaPara)
                    .addComponent(rbtKelvinPara)
                    .addComponent(rbtFahrenheitPara)
                    .addComponent(rbtCelsiusPara))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperaturaDe)
                    .addComponent(lblTemperaturaPara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdTemperaturaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdTemperaturaPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtCelsiusDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtFahrenheitDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtKelvinDe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtCelsiusPara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtFahrenheitPara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtKelvinPara)))
                .addGap(44, 44, 44)
                .addComponent(btnConverter)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterActionPerformed
        double temperaturaDeEntrada;
        Conversor conversor = new Conversor();

        String temperaturaString = tfdTemperaturaDe.getText();
        if (temperaturaString.equals("")) {
            JOptionPane.showMessageDialog(this, "Campo em branco", "Seleção Inválida", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                temperaturaDeEntrada = Double.parseDouble(temperaturaString);

                if (rbtCelsiusDe.isSelected()) {
                    if (rbtFahrenheitPara.isSelected()) {
                        double temperaturaEmFahrenheit = conversor.celsiusParaFahrenheit(temperaturaDeEntrada);
                        tfdTemperaturaPara.setText(String.valueOf(temperaturaEmFahrenheit));
                    } else if (rbtKelvinPara.isSelected()) {
                        double temperaturaEmKelvin = conversor.celsiusParaKelvin(temperaturaDeEntrada);
                        tfdTemperaturaPara.setText(String.valueOf(temperaturaEmKelvin));
                    } else {
                        tfdTemperaturaPara.setText(tfdTemperaturaDe.getText());
                    }
                }
                if (rbtFahrenheitDe.isSelected()) {
                    if (rbtCelsiusPara.isSelected()) {
                        double temperaturaEmCelsius = conversor.fahrenheitParaCelsius(temperaturaDeEntrada);
                        tfdTemperaturaPara.setText(String.valueOf(temperaturaEmCelsius));
                    } else if (rbtKelvinPara.isSelected()) {
                        double temperaturaEmKelvin = conversor.fahrenheitParaKelvin(temperaturaDeEntrada);
                        tfdTemperaturaPara.setText(String.valueOf(temperaturaEmKelvin));
                    } else {
                        tfdTemperaturaPara.setText(tfdTemperaturaDe.getText());
                    }
                }
                if (rbtKelvinDe.isSelected()) {
                    if (rbtCelsiusPara.isSelected()) {
                        double temperaturaEmCelsius = conversor.kelvinParaCelsius(temperaturaDeEntrada);
                        tfdTemperaturaPara.setText(String.valueOf(temperaturaEmCelsius));
                    } else if (rbtFahrenheitPara.isSelected()) {
                        double temperaturaEmFahrenheit = conversor.kelvinParaFahrenheit(temperaturaDeEntrada);
                        tfdTemperaturaPara.setText(String.valueOf(temperaturaEmFahrenheit));
                    } else {
                        tfdTemperaturaPara.setText(tfdTemperaturaDe.getText());
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Digite um número válido", "Seleção Inválida", JOptionPane.WARNING_MESSAGE);
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnConverterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorTemperaturaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorTemperaturaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorTemperaturaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorTemperaturaView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorTemperaturaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgDe;
    private javax.swing.ButtonGroup btgPara;
    private javax.swing.JButton btnConverter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTemperaturaDe;
    private javax.swing.JLabel lblTemperaturaPara;
    private javax.swing.JRadioButton rbtCelsiusDe;
    private javax.swing.JRadioButton rbtCelsiusPara;
    private javax.swing.JRadioButton rbtFahrenheitDe;
    private javax.swing.JRadioButton rbtFahrenheitPara;
    private javax.swing.JRadioButton rbtKelvinDe;
    private javax.swing.JRadioButton rbtKelvinPara;
    private javax.swing.JTextField tfdTemperaturaDe;
    private javax.swing.JTextField tfdTemperaturaPara;
    // End of variables declaration//GEN-END:variables
}
