/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import logic.AdvinhaONumero;

/**
 *
 * @author IFTM
 */
public class AdvinhaONumeroView extends javax.swing.JFrame {

    private final AdvinhaONumero jogo;
    
    public AdvinhaONumeroView() {
        initComponents();
        jogo = new AdvinhaONumero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDificuldade = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblDificuldade = new javax.swing.JLabel();
        lblPalpite = new javax.swing.JLabel();
        tfdPalpite = new javax.swing.JTextField();
        lblDica = new javax.swing.JLabel();
        lblVidas = new javax.swing.JLabel();
        tfdDica = new javax.swing.JTextField();
        tfdVidas = new javax.swing.JTextField();
        btnIniciarJogo = new javax.swing.JButton();
        rbtDificuldadeFacil = new javax.swing.JRadioButton();
        rbtDificuldadeDificil = new javax.swing.JRadioButton();
        rbtDificuldadeMedio = new javax.swing.JRadioButton();
        btnPalpitar = new javax.swing.JButton();
        lblFacil = new javax.swing.JLabel();
        lblMedio = new javax.swing.JLabel();
        lblDificil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDificuldade.setText("Selecione a dificuldade");

        lblPalpite.setLabelFor(tfdPalpite);
        lblPalpite.setText("Seu palpite");

        lblDica.setLabelFor(tfdDica);
        lblDica.setText("Dica");

        lblVidas.setLabelFor(tfdVidas);
        lblVidas.setText("Número de vidas Restantes");

        tfdDica.setEditable(false);

        tfdVidas.setEditable(false);

        btnIniciarJogo.setText("Iniciar jogo");
        btnIniciarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJogoActionPerformed(evt);
            }
        });

        btgDificuldade.add(rbtDificuldadeFacil);
        rbtDificuldadeFacil.setText("Fácil");

        btgDificuldade.add(rbtDificuldadeDificil);
        rbtDificuldadeDificil.setText("Difícil");

        btgDificuldade.add(rbtDificuldadeMedio);
        rbtDificuldadeMedio.setText("Médio");

        btnPalpitar.setText("Palpitar");
        btnPalpitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpitarActionPerformed(evt);
            }
        });

        lblFacil.setLabelFor(rbtDificuldadeFacil);
        lblFacil.setText("(Número de 0 a 10)");

        lblMedio.setLabelFor(rbtDificuldadeMedio);
        lblMedio.setText("(Número de 0 a 100)");

        lblDificil.setLabelFor(rbtDificuldadeDificil);
        lblDificil.setText("(Número de -100 a 100)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblDificuldade))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(lblFacil)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblMedio)))
                            .addGap(18, 18, 18)
                            .addComponent(lblDificil))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(rbtDificuldadeFacil)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                            .addComponent(rbtDificuldadeMedio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                            .addComponent(rbtDificuldadeDificil)
                            .addGap(39, 39, 39)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPalpitar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPalpite)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIniciarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDica)
                                .addGap(18, 18, 18)
                                .addComponent(tfdDica, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblVidas)
                                .addGap(18, 18, 18)
                                .addComponent(tfdVidas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDificuldade)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtDificuldadeFacil)
                    .addComponent(rbtDificuldadeMedio)
                    .addComponent(rbtDificuldadeDificil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacil)
                    .addComponent(lblMedio)
                    .addComponent(lblDificil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnIniciarJogo)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPalpite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPalpitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdDica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDica))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdVidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVidas))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJogoActionPerformed
        if(rbtDificuldadeFacil.isSelected()){
            jogo.setDificuldadeFacil();
            jogo.iniciarJogo();
            tfdVidas.setText(String.valueOf(jogo.getNumeroDeVidas()));
        }
        else if(rbtDificuldadeMedio.isSelected()){
            jogo.setDificuldadeMedio();
            jogo.iniciarJogo();
            tfdVidas.setText(String.valueOf(jogo.getNumeroDeVidas()));
        }
        else if(rbtDificuldadeDificil.isSelected()){
            jogo.setDificuldadeDificil();
            jogo.iniciarJogo();
            tfdVidas.setText(String.valueOf(jogo.getNumeroDeVidas()));
        }
        else {
            JOptionPane.showMessageDialog(this, "Selecione uma dificuldade para iniciar o jogo", "Selecione a dificuldade", JOptionPane.INFORMATION_MESSAGE);
        }
        btnPalpitar.setEnabled(fimDeJogo());
    }//GEN-LAST:event_btnIniciarJogoActionPerformed

    private void btnPalpitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpitarActionPerformed
        
        try {
            int palpite = Integer.parseInt(tfdPalpite.getText());
            int dica = jogo.compararPalpite(palpite);
            
            String msgDica = verificarAcerto(dica);
            tfdDica.setText(msgDica);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Apenas números são permitidos", "Campo preenchido incorretamente", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPalpitarActionPerformed

    private String verificarAcerto(int dica){
        
        btnPalpitar.setEnabled(fimDeJogo());
        System.out.println("Tentativa");
        
        String msgDica = "";
        if(dica >= 1){
            msgDica = "O número correto é menor!";
            jogo.diminuirVida();
        }
        else if(dica == -1){
            msgDica = "O número correto é maior!";
            jogo.diminuirVida();
        }
        else if(dica == 0){
            JOptionPane.showMessageDialog(this, "PARABÉNS!!! Você acertou!", "ACERTOU", JOptionPane.INFORMATION_MESSAGE);
        }
        tfdVidas.setText(String.valueOf(jogo.getNumeroDeVidas()));
        return msgDica;
    }
    
    private boolean fimDeJogo(){
        if(jogo.getNumeroDeVidas() == 1){
            JOptionPane.showMessageDialog(this, "Infelizmente suas vidas acabaram :(", "Sem vidas", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvinhaONumeroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvinhaONumeroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvinhaONumeroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvinhaONumeroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvinhaONumeroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgDificuldade;
    private javax.swing.JButton btnIniciarJogo;
    private javax.swing.JButton btnPalpitar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDica;
    private javax.swing.JLabel lblDificil;
    private javax.swing.JLabel lblDificuldade;
    private javax.swing.JLabel lblFacil;
    private javax.swing.JLabel lblMedio;
    private javax.swing.JLabel lblPalpite;
    private javax.swing.JLabel lblVidas;
    private javax.swing.JRadioButton rbtDificuldadeDificil;
    private javax.swing.JRadioButton rbtDificuldadeFacil;
    private javax.swing.JRadioButton rbtDificuldadeMedio;
    private javax.swing.JTextField tfdDica;
    private javax.swing.JTextField tfdPalpite;
    private javax.swing.JTextField tfdVidas;
    // End of variables declaration//GEN-END:variables
}
